### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by loup15** [pgporada/ansible-playbook-volumio-bluetooth#1]
Hi, forgive I also wrote on PM.
I have a problem with the installation - I'm doing something wrong.
I installed apt-get install ansible
I follow the instructions but I have errors ...

  downloading role '---', owned by
Sorry, --- was not found on galaxy.ansible.com.
  downloading role 'users', owned by -% 20src% 3A% 20singleplatform-eng
Sorry, - src: singleplatform-eng.users was not found on galaxy.ansible.com.
  downloading role 'vim', owned by -% 20src% 3A% 20pg advice
Sorry, - src: pgporada.vim was not found on galaxy.ansible.com.
  downloading role '', owned by ..
Sorry, ... was not found on galaxy.ansible.com.

With the host_prep file
ERROR: Unable to find an inventory file, specify one with -i?

Could you describe the installation method more accurately? I would be grateful, in volumio I miss only bluetooth ...

**Comment by pgporada** [comment]
Hi @loup15,

You ran `sudo apt-get install ansible` and it was successfully installed? Can you show me the output of `ansible --version` please?

The next steps would be 
```
git clone https://github.com/pgporada/ansible-playbook-volumio-bluetooth
cd ansible-playbook-volumio-bluetooth
git pull
ansible-playbook playbook.yml -i hosts -kK
```

**Comment by pgporada** [comment]
Aha. You will need a `hosts` file in your local directory similar to the following
```
[volumios]
192.168.1.100
ansible_connection=ssh
ansible_user=volumio
ansible_ssh_pass=volumio
ansible_become_pass=volumio
```

With that file you can run `ansible-playbook playbook.yml -i hosts -kK`.

**Comment by loup15** [comment]
Thank you for the quick reply :)

Of course, ansible has been installed: ansible 1.7.2
I created the host.

Attempting to execute the command: ansible-playbook playbook.yml -i hosts -kK
Then he asks for the password twice - I give it and then:

volumio@volumio:~/ansible-playbook-volumio-bluetooth$` ansible-playbook playbook.yml -i hosts -kK

SSH password:
sudo password [defaults to SSH password]:
ERROR: become is not a legal parameter at this level in an Ansible Playbook
volumio@volumio:~/ansible-playbook-volumio-bluetooth$

**Comment by loup15** [comment]
I updated the ansimble:
volumio@volumio:~$ ansible --version
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/volumio/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.9 (default, Sep 26 2018, 05:58:52) [GCC 4.9.2]

But unfortunately ...

volumio@volumio:~/ansible-playbook-volumio-bluetooth$ ansible-playbook playbook.yml -i hosts -kK
SSH password:
BECOME password[defaults to SSH password]:
ERROR! vars file defaults/main.yaml was not found
Could not find file on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option


I also found errors in the file names: main.yaml instead of maui.yml

**Comment by pgporada** [comment]
Run a `git pull` and then try to deploy the code again. I had used the `.gitignore` file to prevent syncing my personal `defaults/main.yaml` to this repo because it has user creds. There's now a blank file in its place.

**Comment by loup15** [comment]
I changed the content of the playbook.yml file - I added the path:
  vars_files:
     - roles / ansible-role-volumio-bluetooth / defaults / main.yml
Something worked :) it took a while and ended, but with warnings.

Now I check what happened and what works :)

**Comment by pgporada** [comment]
Try to pair your phone following the `sudo bluetoothctl` instructions and let me know how it goes!

**Comment by loup15** [comment]
[bluetooth]# show
Controller B8:27:EB:56:0B:55 (public)
        Name: volumio
        Alias: volumio
        Class: 0x00040000
        Powered: yes
        Discoverable: no
        DiscoverableTimeout: 0x000000b4
        Pairable: yes
        UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
        UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
        UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
        UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
        UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
        Modalias: usb:v1D6Bp0246d0534
        Discovering: no
Advertising Features:
        ActiveInstances: 0x00
        SupportedInstances: 0x05
        SupportedIncludes: tx-power
        SupportedIncludes: appearance
        SupportedIncludes: local-name

I paired the phone :) sees volumio as an audio player, and can be connected.
Unfortunately - playback, e.g. youtube does not switch volumio to BT mode ... and I can't hear anything from the speakers (standard playlist from volumio is going, not BT ...)

**Comment by pgporada** [comment]
Shut off the volumio playlist, turn up the volume in volumio, then try to play youtube on your phone.

**Comment by pgporada** [comment]
```
[bluetooth]# show
Controller B8:27:EB:7F:DF:6F (public)
	Name: barntunes
	Alias: barntunes
	Class: 0x0004041c
	Powered: yes
	Discoverable: no
	DiscoverableTimeout: 0x000000b4
	Pairable: yes
	UUID: Generic Attribute Profile (00001801-0000-1000-8000-00805f9b34fb)
	UUID: Audio Sink                (0000110b-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control        (0000110e-0000-1000-8000-00805f9b34fb)
	UUID: PnP Information           (00001200-0000-1000-8000-00805f9b34fb)
	UUID: Generic Access Profile    (00001800-0000-1000-8000-00805f9b34fb)
	UUID: A/V Remote Control Target (0000110c-0000-1000-8000-00805f9b34fb)
	Modalias: usb:v1D6Bp0246d0534
	Discovering: no
Advertising Features:
	ActiveInstances: 0x00
	SupportedInstances: 0x05
	SupportedIncludes: tx-power
	SupportedIncludes: appearance
	SupportedIncludes: local-name

[bluetooth]# devices
Device xx:xx:xx:xx:xx:xx Phil's Phone
```

**Comment by loup15** [comment]
Ok, after clearing the list and rebooting the system, I paired the phone, and it actually plays BT :) it's a success :) unfortunately you can't control volumio then. As long as it plays BT and the phone is connected nothing with volumio other will not let go. Only after disconnecting BT.

Generally, for my beginning this is not bad .. but I have to think about how to integrate more tightly - that both volumio and BT can be used :)
Anyway, good job :)

**Comment by loup15** [comment]
And you can have both a playlist and BT? And it skips depending on the source?

**Comment by loup15** [comment]
You have another class of BT.. hmmm

**Comment by pgporada** [comment]
`As long as it plays BT and the phone is connected nothing with volumio other will not let go. Only after disconnecting BT.` 
If you hit play in the volumio interface, then volumio will regain control.

`And you can have both a playlist and BT? And it skips depending on the source?`
I don't think so, but I haven't tried it

`You have another class of BT.. hmmm`
No idea. Mine is a pi3b+ I think?

**Comment by pgporada** [comment]
The way that we use this is I walk into my shop/wife's craftroom/etc while listening to a book on the phone, open the volumio interface, pause whatever song is playing, and finally connect my phone to the bluetooth to continue listening to the book. When I'm done, I reverse that process.

**Comment by loup15** [comment]
I also have pi3B +, change of class is easy:
sudo hciconfig hc0 class 0x04041c

I care more about BT being detectable as another source in Volumio - just like it works in Premium.
Well - maybe I'll come up with something :) Thank you for your help! Good job :)
