### ISSUE TITLE
Host configs need to be on one line?

### ISSUE THREAD

**Issue by erichgoldman** [pgporada/ansible-playbook-volumio-bluetooth#2]
I am looking at the [hosts.example](https://github.com/pgporada/ansible-playbook-volumio-bluetooth/blob/07fbb876640c7b668083ea2c01029ff159ffdf6a/hosts.example#L2) and I see an IP on the second line, then config variables on their own lines.

I don't use ansible very much, but I think these all need to be on the same line space separted. The config did not work for me as it currently is in the repo, when I put them all on one line like

```
[volumios]
X.X.X.X ansible_connection=ssh ansible_user=volumio ansible_ssh_pass=volumio ansible_become_pass=volumio
```

then it worked, still prompted me for password, but then everything else ran as expected.

Wanted to double check on this before I send a PR

**Comment by pgporada** [comment]
What version of ansible are you on?

**Comment by pgporada** [comment]
Oh, yeah it's totally wrong as is. It should be 
```
[volumios]
192.168.1.100

[volumios:vars]
ansible_connection=ssh
ansible_user=volumio
ansible_ssh_pass=volumio
ansible_become_pass=volumio
```
