### ISSUE TITLE
Connected but no audio output

### ISSUE THREAD

**Issue by savjanivv** [pgporada/ansible-playbook-volumio-bluetooth#4]
Hi,

Firstly great work on this! I've been trying to get this working for a few days and this script really sped things up.

I'm having a problem getting any output over BT. My set up is a RPI 3B+ with HifiBerry Amp2. I can hear audio directly from Volumio and the Spotify Connect2 plugin, but not with anything played over bluetooth. Followed the steps exactly from your post. Any other suggestions?

**Comment by taliesin** [comment]
Just ran into the same problem using an external sound card on USB. The bluealsa-play@.service (located in /lib/systemd/system) states the device to play audio on.
So use aplay -l to list your output devices and change the ExecStart line in the file accordingly.

For me it was:
`ExecStart=/usr/bin/bluealsa-aplay --profile-a2dp %I -D default:CARD=D3`

You probably want to fix the Description entry as-well.

Then restart the service using
`sudo systemctl restart bluealsa-aplay@{your bluetooth device ID here}`

**Comment by savjanivv** [comment]
Great! That worked a treat!
