### ISSUE TITLE
ERROR: become is not a legal parameter at this level in an Ansible Playbook

### ISSUE THREAD

**Issue by 8user8** [pgporada/ansible-playbook-volumio-bluetooth#5]
Hi,
sadly this is not working on my fresh install.
At this step

# Run ansible from your computer to configure the Volumio server
ansible-playbook playbook.yml -i hosts.example -kK

it returns:

ERROR: become is not a legal parameter at this level in an Ansible Playbook

Any advise how to get it working?

btw.: before I tried " Super-Simple-Raspberry-Pi-Audio-Receiver-Install " and realized it's outdated...

**Comment by pgporada** [comment]
What version of ansible are you using? I'm not at a computer right now, but
I will help as soon as I can.

**Comment by pgporada** [comment]
What OS are you running too? I suspect you have a **very** old version of ansible (pre 2.x.x). FWIW I rebuilt one of my volumios a few weekends ago with this.

Can you provide the output from the following commands please?
```
uname -a
cat /etc/os-release
lsb_release -a
ansible --version
```

**Comment by 8user8** [comment]
Yes, I can ;)

volumio@volumio_essbar:~$ uname -a
Linux volumio_essbar 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l              GNU/Linux
volumio@volumio_essbar:~$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
VOLUMIO_BUILD_VERSION="168ba7444df98cd868db72f24faec0b6346489cc"
VOLUMIO_FE_VERSION="847a48ecf32d35cc502a0053d585d1a69236e391"
VOLUMIO_BE_VERSION="03f7bbd984817e093cac62b7ff876f3c2cfabc1d"
VOLUMIO_ARCH="arm"
VOLUMIO_VARIANT="volumio"
VOLUMIO_TEST="FALSE"
VOLUMIO_BUILD_DATE="Tue Dec 22 14:39:52 CET 2020"

VOLUMIO_VERSION="2.861"
VOLUMIO_HARDWARE="pi"
VOLUMIO_HASH="097e28ee6263e31d0bf6b690a02dcab3"
volumio@volumio_essbar:~$ lsb_release -a
-bash: lsb_release: command not found
volumio@volumio_essbar:~$ ansible --version
ansible 1.7.2


But there's nothing crossed out, don't know why it appears here.

**Comment by pgporada** [comment]
Try upgrading to the latest ansible available. Worst case scenario, install
it via python pip. You have ansible 1.7.4 currently installed and it's so
old which is the reason you received the initial error. I'm willing to bet
that upgrading to ansible 2.x will solve your problem. Let me know if it
doesn't and we'll figure out a way to work together and get you on your way
to blasting some tunes.

**Comment by 8user8** [comment]
Hi, thx for support.
For now I got the installtion and pairing process working / done.
Updating ansible has done the trick ;)
But I don't get any audio out of volumio. Tested with 2 devices (phone + laptop) and for shure, stopped playback from volumios interface.
Any ideas how to troubleshoot?

Additional info: I also connected the raspberry by wire and turned off wifi. It's a raspberry 3b.

**Comment by pgporada** [comment]
Yeah I can help you out!

1. What type of audio DAC are you using?
2. Are you just attaching an aux cable to some speakers?
3. Are you trying to play back music directly from the Volumio web
interface? If so, I _don't think_ that Volumio supports that.

**Comment by 8user8** [comment]
oh, sorry, some other thingsbeen more important, so I forgot my issue ^^

1. It's an USB-DAC
2. No
3. I don't really know what you mean. I tried to just playback via Bluetooth-audio from laptop or phone (with stopped playback in volumios interface)

**Comment by pgporada** [comment]
@8user8 Check out moode audio, it does everything volumio does, but better. It has built in bluetooth support too.
