### ISSUE TITLE
Error installing dh-autoreconf

### ISSUE THREAD

**Issue by tarheels100** [pgporada/ansible-playbook-volumio-bluetooth#6]
I get the following output when running the `ansible-playbook` command:

> PLAY [volumios] ********************************************************************************************************
> 
> TASK [Gathering Facts] *************************************************************************************************
> ok: [volumio.lan]
> 
> TASK [roles/ansible-role-volumio-bluetooth : Install packages] *********************************************************
> fatal: [volumio.lan]: FAILED! => {"cache_update_time": 1620146565, "cache_updated": true, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'vim' 'dh-autoreconf' 'libortp-dev' 'libusb-dev' 'libudev-dev' 'libical-dev' 'libreadline-dev' 'libsbc-dev'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n dh-autoreconf : Depends: debhelper but it is not going to be installed\n                 Depends: libtool (>= 2.4.2) but it is not going to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " dh-autoreconf : Depends: debhelper but it is not going to be installed", "                 Depends: libtool (>= 2.4.2) but it is not going to be installed"]}
>         to retry, use: --limit @/home/austin/volumio-bluetooth/ansible-playbook-volumio-bluetooth/playbook.retry
> 
> PLAY RECAP *************************************************************************************************************
> volumio.lan                : ok=1    changed=0    unreachable=0    failed=1

I'm running Volumio version 2.882 on a Raspberry Pi 4.

**Comment by pgporada** [comment]
I'm on v2.6xx from 2019. I'm updating my barn volumio now and will try running the playbook against it again. It'll be a bit because I'm working at this moment.

**Comment by pgporada** [comment]
What happens when you ssh to the volumio and manually run the following:
```
sudo apt update
sudo apt install dh-autoreconf
```

I see your output has `you have held broken packages`, but what are your broken packages?

**Comment by tarheels100** [comment]
Thanks for helping out with this!

```
volumio@volumio:~$ sudo apt install dh-autoreconf
[sudo] password for volumio:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 dh-autoreconf : Depends: debhelper but it is not going to be installed
                 Depends: libtool (>= 2.4.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
I'm no expert on package management, but I read that you can run this to see what packages are being "held":
`volumio@volumio:~$ dpkg --get-selections | grep hold`
This returns no matches.

**Comment by pgporada** [comment]
Here's the `debhelper` and `libtool` versions I have.

```
phil@barntunes:~$ dpkg -l | grep libtool
ii  libltdl-dev:armhf                    2.4.2-1.11                         armhf        System independent dlopen wrapper for GNU libtool
ii  libltdl7:armhf                       2.4.2-1.11                         armhf        System independent dlopen wrapper for GNU libtool
ii  libtool                              2.4.2-1.11                         all          Generic library support script
phil@barntunes:~$ dpkg -l | grep debhelper
ii  debhelper                            10.2.2~bpo8+1                      all          helper programs for debian/rules
ii  dh-autoreconf                        12~bpo8+1                          all          debhelper add-on to call autoreconf and clean up after the build
ii  dh-strip-nondeterminism              0.003-1                            all          debhelper add-on to strip non-determinism from files
```

Can you try `sudo apt install debhelper libtool` ? The worst thing that happens is you'll have to reinstall volumio, but eh I'm right there with you.

**Comment by tarheels100** [comment]
Here's what I see:
```
volumio@volumio:~$ dpkg -l | grep debhelper
volumio@volumio:~$ dpkg -l | grep libtool
ii  libltdl7:armhf                       2.4.2-1.11                         armhf        System independent dlopen wrapper for GNU libtool
```
When I try installing these packages, I get:
```
volumio@volumio:~$ sudo apt install debhelper libtool
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 debhelper : Depends: binutils but it is not going to be installed
             Depends: dpkg-dev (>= 1.17.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Should I keep following the rabbit hole and trying installing these as well?

**Comment by pgporada** [comment]
Yeah, let's see where it goes.
```
phil@barntunes:~$ dpkg -l | grep binutils
ii  binutils                             2.25-5+deb8u1                      armhf        GNU assembler, linker and binary utilities
phil@barntunes:~$ dpkg -l | grep dpkg-dev
ii  dpkg-dev                             1.17.27                            all          Debian package development tools
```

**Comment by pgporada** [comment]
In the meantime, I'm making sure to get the latest `bluez` and .so files linked.

**Edit:** This part went smoothly. https://github.com/pgporada/ansible-playbook-volumio-bluetooth/commit/15585265000ec6f8748c466cfdd6fd0ff31fa4d6

**Comment by pgporada** [comment]
For me this thing has been rock solid since I put it up 2+ years ago and I have 3 of the same system.

**Comment by pgporada** [comment]
@tarheels100 I pushed a few ansible changes, one of which _should_ get the dependencies you need. https://github.com/pgporada/ansible-playbook-volumio-bluetooth/commit/2daef7c8a75f66f010d74bb33d5c98b9f8d5396d

**Comment by pgporada** [comment]
I've got meetings so I won't be able to get back to you until later tonight or tomorrow.

**Comment by tarheels100** [comment]
`binutils` and `dpkg-dev` installed fine.  However, installing `binutils` removed `libc6-dev`, which causes this problem:

```
volumio@volumio:~$ sudo apt install debhelper libtool
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libtool : Depends: libc6-dev but it is not going to be installed or
                    libc-dev
E: Unable to correct problems, you have held broken packages.
```

No luck installing these dependencies due to version conflicts:
```
volumio@volumio:~$ sudo apt install libc6-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Depends: libc6 (= 2.19-18+deb8u10) but 2.24-11+deb9u4 is to be installed
             Depends: libc-dev-bin (= 2.19-18+deb8u10) but 2.24-11+deb9u4 is to be installed
E: Unable to correct problems, you have held broken packages.

volumio@volumio:~$ sudo apt install libc-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libc6-dev' instead of 'libc-dev'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Depends: libc6 (= 2.19-18+deb8u10) but 2.24-11+deb9u4 is to be installed
             Depends: libc-dev-bin (= 2.19-18+deb8u10) but 2.24-11+deb9u4 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I'll try out your new version while you're away and let you know how it goes.  Thanks again!

**Comment by tarheels100** [comment]
Unfortunately, no luck with the new ansible script:

> PLAY [volumios] ********************************************************************************************************
> 
> TASK [Gathering Facts] *************************************************************************************************
> ok: [volumio.lan]
> 
> TASK [roles/ansible-role-volumio-bluetooth : Install packages] *********************************************************
> fatal: [volumio.lan]: FAILED! => {"cache_update_time": 1620151539, "cache_updated": true, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'vim' 'libtool' 'debhelper' 'dh-autoreconf' 'libortp-dev' 'libusb-dev' 'libglib2.0-dev' 'libudev-dev' 'libical-dev' 'libreadline-dev' 'libsbc-dev' -o APT::Install-Recommends=yes' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n libglib2.0-dev : Depends: libpcre3-dev (>= 1:8.31) but it is not going to be installed\n                  Depends: zlib1g-dev but it is not going to be installed\n libtool : Depends: libc6-dev but it is not going to be installed or\n                    libc-dev\n libusb-dev : Depends: libc6-dev but it is not going to be installed or\n                       libc-dev\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " libglib2.0-dev : Depends: libpcre3-dev (>= 1:8.31) but it is not going to be installed", "                  Depends: zlib1g-dev but it is not going to be installed", " libtool : Depends: libc6-dev but it is not going to be installed or", "                    libc-dev", " libusb-dev : Depends: libc6-dev but it is not going to be installed or", "                       libc-dev"]}
>         to retry, use: --limit @/home/austin/volumio-bluetooth/ansible-playbook-volumio-bluetooth/playbook.retry
> 
> PLAY RECAP *************************************************************************************************************
> volumio.lan                : ok=1    changed=0    unreachable=0    failed=1

**Comment by pgporada** [comment]
I will install a volume from scratch tonight and get this sorted.

**Comment by tarheels100** [comment]
Hi @pgporada, I was curious how installing from scratch worked out.  If you haven't gotten to it, I totally understand; you've been more than generous with your time already.  If you think it could be helpful, I could try installing the newest Volumio from scratch to see if this makes any difference for me.

**Comment by pgporada** [comment]
@tarheels100 I just booted up a volumio box. It's been a weekend. The baby popped out two brand new front teeth and that means inconsolable crying and pain.

**Comment by tarheels100** [comment]
I feel you on that, I've got a 4 month old myself and that's a full time job on its own.  Congrats on the new milestone though; hopefully calmer times are right around the corner!  Anyway, please don't feel pressured for my sake, I can wait.

**Comment by pgporada** [comment]
Ansible is running against this little pi with the latest volumio img now. I'll ping you when I've got a proper fix.

**Comment by pgporada** [comment]
@tarheels100 I've made progress by adding the debian/stretch repositories to /etc/apt/sources.list. I had to do this because the volumio build on debian/jessie (newer) doesn't have the all the correct dependency resolution that debian/stretch had meaning they most likely didn't build all the packages on jessie.

What does this mean? It's a crap shoot if the automatic updater will function into the future - probably, but be warned. You will no longer be able to automatically update the underlying system, but I think that was already a given with volumio?

**Comment by tarheels100** [comment]
@pgporada I've heard that Volumio uses a pretty convoluted mix of packages from different debian releases, so I guess that fits with what you're seeing.

The inability to update is probably not a big deal since once things work, I'll probably mostly leave it alone.

**Comment by pgporada** [comment]
This thing has turned into a big tangled nightmare. I've gotten no further in the past 2 weeks. I think what I need to do is poke upstream and see if they can provide the missing system packages.

**Comment by tarheels100** [comment]
Ugh, sounds rough.  I'm guessing it would help if Volumio would sort out their package version issues.

**Comment by pgporada** [comment]
If you can get volumio circa v2.6xx from 2019 this should work flawlessly 😆. I'll poke you again when I get an update from Volumio.

**Comment by tarheels100** [comment]
When I get a chance, I'll give that a try.  I found links to older versions [here](https://community.volumio.org/t/older-volumio-versions-img-files/6344/3).  I'm assuming there isn't much difference between the current version and 2.6?

**Comment by pgporada** [comment]
I'm sure there is under the hood. One thing that's new, but works poorly on
mobile (IMO), is the UI. I immediately set it back to classic mode.

**Comment by tarheels100** [comment]
Hi again, I hope you're doing well!  I took your advice and installed an older version of Volumio (2.698).  Now, the ansible script completes without error.  I paired my phone using bluetoothctl, and the phone confirms that it is connected for audio.  However, I don't get any audio out of the rpi when playing music from my phone.  Playing music through Volumio works fine, so I know it is at least capable of making sound.  Does the bluetooth audio default to the same audio device as Volumio?  FYI, I'm using a knock-off Hifiberry DAC over I2S.

**Comment by pgporada** [comment]
Weird. I assume you've tried turning up the volume on your phone and upped the volume in the volumio interface? You should get sound out of the pi. I use several Hifiberry DAC Pluses throughout the house.

**Comment by pgporada** [comment]
@tarheels100 Switch to moode audio, it does everything that volumio does, but better. It has built in bluetooth support too.

**Comment by tarheels100** [comment]
> Weird. I assume you've tried turning up the volume on your phone and upped the volume in the volumio interface? You should get sound out of the pi. I use several Hifiberry DAC Pluses throughout the house.

I tried upping the volume on my phone as well as in volumio, but never got any sound out.  My phone recognizes the bluetooth connection and tries to route audio to it.  Maybe there's some difference with using a RPi4?  Not sure what type you use.

> @tarheels100 Switch to moode audio, it does everything that volumio does, but better. It has built in bluetooth support too.

The issue with moode audio is that it doesn't have a Pandora plugin like volumio does.  I've searched around quite a bit, but haven't found any pre-built software that has both Pandora and bluetooth support. 🤷 Anyway, thanks for all your help!
